### ISSUE TITLE
Thanks ;)

### ISSUE THREAD

**Issue by andresgarcia0313** [solo5star/BatteryPercentage#1]
Check your code and there are improvements to be made, the first is to generate the installer and that only the installer shows advertising (only in the installer), the second is to visually improve the numbers of the icon and insist users on functional improvements that they also propose to separate in layers and classes your application to leave the execution timer separate from the application logic

**Comment by solo5star** [comment]
Hi.

You've posted issues elsewhere, but I'll reply all in this comment.

To be honest, these codes are referenced from elsewhere, so I don't understand almost of them even though I wrote. In addition to this, I have not been using C# these days.

Maybe this project is not able to continue, due to various factors.

So this project will be discontinued. (Because of my limitation. lack of C#/Windows API knowledge)

Thanks for posting issues. If you want, you can continue the work by fork this project.
